version: '3.9'

services:
  #mongo_db:
  #  container_name: back3
  #  image: mongo:latest
  #  ports:
  #    - 27017:27017

  api:
    container_name: api_backiii
    build: .
    ports:
      - 8003:8003
    environment:
      #MONGO_URI: 
      MONGO_URI: mongodb+srv://admin:admin@cluster0.kbqmp.mongodb.net/back3?retryWrites=true&w=majority&appName=Cluster0